# Gradle Properties
org.gradle.java.home=D:\\Users\\redbl\\Downloads\\1.20.1_modern_beta\\.fabric\\server\\zulu17.42.19-ca-jdk17.0.7-win_x64\\zulu17.42.19-ca-jdk17.0.7-win_x64
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 1.1
maven_group = net.mine_diver
archives_base_name = Macula

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = b1.7.2
loader_version = 0.16.0

osl_version = 0.16.0
